--- a/source/makefile
+++ b/source/makefile
@@ -136,10 +136,17 @@
 #
 
 
-CC = mpicc -O3 -xHOST -ip -no-prec-div -openmp -I/opt/intel/mkl/include/fftw
-FC = mpif90 -O3 -xHOST -ip -no-prec-div -openmp
-LIB= -L/opt/intel/mkl/lib -mkl=parallel -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -lpthread -lifcore -lmpi -lmpi_f90 -lmpi_f77
 
+include /usr/share/dpkg/default.mk
+ifeq ($(DEB_HOST_MULTIARCH),amd64)
+DEB_SSE =
+else
+DEB_SSE = -Dnosse
+endif
+
+CC    = mpicc `dpkg-buildflags --get CPPFLAGS` `dpkg-buildflags --get CFLAGS` $(DEB_SSE) -fopenmp
+FC    = mpif90 `dpkg-buildflags --get CPPFLAGS` `dpkg-buildflags --get FFLAGS` -fopenmp
+LIB   = -lfftw3 -llapack -lblas `dpkg-buildflags --get LDFLAGS`
 
 
 
@@ -242,15 +249,14 @@
 #
 
 PROG    = openmx
-DESTDIR = ../work
-UTIL 	= DosMain jx analysis_example esp polB bandgnu13 bin2txt cube2xsf intensity_map md2axsf
+UTIL 	= DosMain bandgnu13
 
 #
 # OpenMX
 #
 
 openmx:	$(OBJS)
-	$(CC) $(OBJS) $(STACK) $(LIB) -lm -o openmx
+	$(FC) $(OBJS) $(STACK) $(LIB) -lm -o openmx
 
 #
 #
@@ -259,7 +265,6 @@
 #
 
 all: $(PROG) $(UTIL)
-	cp $(PROG) $(UTIL) $(DESTDIR)/
 
 openmx.o: openmx.c openmx_common.h tran_variables.h tran_prototypes.h
 	$(CC) -c openmx.c
@@ -659,9 +664,9 @@
 #
 #
 
-install: $(PROG)
-	strip $(PROG)
-	cp $(PROG) $(DESTDIR)/$(PROG)
+install: $(PROG) $(UTIL)
+	mkdir -p $(DESTDIR)/usr/bin/
+	cp $(PROG) $(UTIL) $(DESTDIR)/usr/bin/
 
 #
 #
@@ -680,7 +685,6 @@
 
 DosMain: DosMain.o Inputtools.o malloc_multidimarray.o Tetrahedron_Blochl.o 
 	$(CC) -o $@ DosMain.o Inputtools.o malloc_multidimarray.o Tetrahedron_Blochl.o -lm 
-	cp DosMain $(DESTDIR)/DosMain
 
 DosMain.o :DosMain.c openmx_common.h
 	$(CC) -o $@ -c DosMain.c
@@ -695,7 +699,6 @@
 
 jx: jx.o read_scfout.o Eigen_lapack.o 
 	$(CC) jx.o read_scfout.o $(LIB) -lm -o jx
-	cp jx $(DESTDIR)/jx
 
 jx.o: jx.c read_scfout.h 
 	$(CC) -c jx.c
@@ -708,7 +711,6 @@
 
 analysis_example: analysis_example.o read_scfout.o
 	$(CC) analysis_example.o read_scfout.o $(LIB)  -lm -o analysis_example
-	cp analysis_example $(DESTDIR)/analysis_example
 
 analysis_example.o: analysis_example.c read_scfout.h 
 	$(CC) -c analysis_example.c
@@ -725,7 +727,6 @@
 OBJS_ESP  = esp.o Inputtools.o
 esp:	$(OBJS_ESP)
 	$(CC) $(OBJS_ESP) $(LIB) -lm -o $@
-	cp esp $(DESTDIR)/esp
 esp.o : esp.c Inputtools.h
 	$(CC) -o $@ -c esp.c
 
@@ -737,7 +738,6 @@
 
 check_lead: check_lead.o Inputtools.o
 	$(CC) check_lead.o Inputtools.o -lm -o check_lead
-	cp check_lead $(DESTDIR)/check_lead
 
 check_lead.o: check_lead.c Inputtools.h 
 	$(CC) -c check_lead.c
@@ -751,7 +751,6 @@
 OpticalConductivityMain: OpticalConductivityMain.o \
               Inputtools.o  malloc_multidimarray.o
 	$(CC) -o $@   OpticalConductivityMain.o  Inputtools.o  malloc_multidimarray.o -lm 
-	cp OpticalConductivityMain $(DESTDIR)/OpticalConductivityMain
 
 #
 #
@@ -762,7 +761,6 @@
 OBJS_polB = polB.o read_scfout.o
 polB:	$(OBJS_polB)
 	$(CC) $(OBJS_polB) $(LIB) -lm -o polB
-	cp polB $(DESTDIR)/polB
 
 polB.o: polB.c read_scfout.h 
 	$(CC) -c polB.c
@@ -775,7 +773,6 @@
 
 test_mpi: test_mpi.o
 	$(CC) test_mpi.o $(LIB) -lm -o test_mpi
-	cp test_mpi $(DESTDIR)/test_mpi
 
 test_mpi.o: test_mpi.c
 	$(CC) -c test_mpi.c
